/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/PrivacyPopup copy.vue')['default']
    DateQuery: typeof import('./components/DateQuery.vue')['default']
    DemoBlock: typeof import('./components/DemoBlock.vue')['default']
    'DemoBlock copy': typeof import('./components/DemoBlock copy.vue')['default']
    GlobalDialog: typeof import('./components/GlobalDialog.vue')['default']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    GlobalMessage: typeof import('./components/GlobalMessage.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    ListEmpty: typeof import('./components/ListEmpty.vue')['default']
    PaginationBar: typeof import('./components/PaginationBar.vue')['default']
    PrivacyPopup: typeof import('./components/PrivacyPopup.vue')['default']
    'PrivacyPopup copy': typeof import('./components/PrivacyPopup copy.vue')['default']
    SkeletonPage: typeof import('./components/SkeletonPage.vue')['default']
    SliderCaptcha: typeof import('./components/SliderCaptcha.vue')['default']
    StatusBadge: typeof import('./components/StatusBadge.vue')['default']
    UniEcharts: typeof import('uni-echarts')['default']
    WdActionSheet: typeof import('@wot-ui/ui/components/wd-action-sheet/wd-action-sheet.vue')['default']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['default']
    WdCell: typeof import('@wot-ui/ui/components/wd-cell/wd-cell.vue')['default']
    WdCellGroup: typeof import('@wot-ui/ui/components/wd-cell-group/wd-cell-group.vue')['default']
    WdConfigProvider: typeof import('@wot-ui/ui/components/wd-config-provider/wd-config-provider.vue')['default']
    WdDialog: typeof import('@wot-ui/ui/components/wd-dialog/wd-dialog.vue')['default']
    WdGap: typeof import('@wot-ui/ui/components/wd-gap/wd-gap.vue')['default']
    WdIcon: typeof import('@wot-ui/ui/components/wd-icon/wd-icon.vue')['default']
    WdNotify: typeof import('@wot-ui/ui/components/wd-notify/wd-notify.vue')['default']
    WdPopup: typeof import('@wot-ui/ui/components/wd-popup/wd-popup.vue')['default']
    WdSwitch: typeof import('@wot-ui/ui/components/wd-switch/wd-switch.vue')['default']
    WdTabbar: typeof import('@wot-ui/ui/components/wd-tabbar/wd-tabbar.vue')['default']
    WdTabbarItem: typeof import('@wot-ui/ui/components/wd-tabbar-item/wd-tabbar-item.vue')['default']
    WdToast: typeof import('@wot-ui/ui/components/wd-toast/wd-toast.vue')['default']
  }
}
