import type { ReviewTask } from "./types";

const baseAttrs = {
  partNo: "",
  name: "",
  spec: "",
  material: "",
  unit: "",
  system: "",
  device: "",
  installLocation: "",
  category: "",
  level: "",
  importance: "",
  radiationRisk: "",
};

/** 复核任务 mock 数据（复刻原型 mockReviewTasks 结构） */
export const mockReviewTasks: ReviewTask[] = [
  {
    id: "task-001",
    documentId: "d-001",
    documentName: "泵 P-101 维修手册 V2.1.pdf",
    documentNo: "DOC-2026-0087",
    fileType: "PDF",
    totalPages: 3,
    currentPage: 1,
    candidates: [
      {
        id: "cand-1",
        pageNo: 1,
        label: "驱动端轴承 6208-2RS",
        status: "pending",
        bbox: { x: 30, y: 25 },
        isPart: true,
        candidateType: "备件",
        partAttributes: { ...baseAttrs, partNo: "P101-001", name: "轴承", spec: "6208-2RS", material: "GCr15", unit: "1#机组", system: "给水系统", device: "泵 P-101", installLocation: "泵驱动端", category: "机械", level: "A级", importance: "关键", radiationRisk: "低" },
      },
      {
        id: "cand-2",
        pageNo: 1,
        label: "非驱动端轴承 6207-2RS",
        status: "pending",
        bbox: { x: 62, y: 35 },
        isPart: true,
        candidateType: "备件",
        partAttributes: { ...baseAttrs, partNo: "P101-002", name: "轴承", spec: "6207-2RS", material: "GCr15", unit: "1#机组", system: "给水系统", device: "泵 P-101", installLocation: "泵非驱动端", category: "机械", level: "A级", importance: "关键", radiationRisk: "低" },
      },
      {
        id: "cand-3",
        pageNo: 1,
        label: "安全提示：断电挂牌",
        status: "confirmed",
        bbox: { x: 20, y: 70 },
        isPart: false,
        candidateType: "安全提示",
        partAttributes: { ...baseAttrs },
      },
      {
        id: "cand-4",
        pageNo: 2,
        label: "密封垫 DN50 PN16",
        status: "pending",
        bbox: { x: 45, y: 30 },
        isPart: true,
        candidateType: "零件",
        isIncomplete: true,
        partAttributes: { ...baseAttrs, partNo: "V201-005", name: "密封垫", spec: "DN50 PN16", unit: "1#机组", system: "蒸汽系统", device: "主汽阀 MV-201", category: "机械", level: "B级", importance: "重要", radiationRisk: "中" },
      },
      {
        id: "cand-5",
        pageNo: 3,
        label: "检查周期 8000 小时",
        status: "pending",
        bbox: { x: 55, y: 50 },
        isPart: false,
        candidateType: "操作步骤",
        partAttributes: { ...baseAttrs },
      },
    ],
  },
  {
    id: "task-002",
    documentId: "d-002",
    documentName: "主汽阀 MV-201 总装图.dwg",
    documentNo: "DWG-2026-0091",
    fileType: "DWG",
    totalPages: 2,
    currentPage: 1,
    candidates: [
      {
        id: "cand-6",
        pageNo: 1,
        label: "阀盖密封圈 Φ140×Φ160",
        status: "confirmed",
        bbox: { x: 40, y: 30 },
        isPart: true,
        candidateType: "零件",
        partAttributes: { ...baseAttrs, partNo: "V201-006", name: "L型密封圈", spec: "Φ140×Φ160", material: "氟橡胶", unit: "2#机组", system: "蒸汽系统", device: "主汽阀 MV-201", installLocation: "阀杆密封", category: "机械", level: "B级", importance: "重要", radiationRisk: "中" },
      },
      {
        id: "cand-7",
        pageNo: 1,
        label: "阀杆材质 17-4PH",
        status: "rejected",
        bbox: { x: 65, y: 55 },
        isPart: true,
        partAttributes: { ...baseAttrs, partNo: "V201-007", name: "阀杆", spec: "17-4PH", material: "沉淀硬化不锈钢", unit: "2#机组", system: "蒸汽系统", device: "主汽阀 MV-201", category: "机械", level: "A级", importance: "关键", radiationRisk: "中" },
      },
      {
        id: "cand-8",
        pageNo: 2,
        label: "执行机构气缸 O 型圈",
        status: "pending",
        bbox: { x: 35, y: 60 },
        isPart: true,
        candidateType: "备件",
        partAttributes: { ...baseAttrs, partNo: "V201-008", name: "O型圈", spec: "Φ100×5.3", material: "NBR", unit: "2#机组", system: "蒸汽系统", device: "主汽阀 MV-201", installLocation: "执行机构", category: "机械", level: "C级", importance: "一般", radiationRisk: "低" },
      },
    ],
  },
  {
    id: "task-003",
    documentId: "d-006",
    documentName: "电机 M-105 碳刷更换工艺.pdf",
    documentNo: "SOP-2026-0102",
    fileType: "PDF",
    totalPages: 2,
    currentPage: 1,
    candidates: [
      {
        id: "cand-9",
        pageNo: 1,
        label: "碳刷 D374N 25×32×60",
        status: "pending",
        bbox: { x: 30, y: 40 },
        isPart: true,
        candidateType: "备件",
        partAttributes: { ...baseAttrs, partNo: "M105-012", name: "碳刷", spec: "D374N 25×32×60", material: "电化石墨", unit: "1#机组", system: "电气系统", device: "电机 M-105", installLocation: "集电环", category: "电气", level: "C级", importance: "一般", radiationRisk: "低" },
      },
      {
        id: "cand-10",
        pageNo: 2,
        label: "集电环磨损量检查",
        status: "pending",
        bbox: { x: 50, y: 35 },
        isPart: false,
        candidateType: "操作步骤",
        partAttributes: { ...baseAttrs },
      },
    ],
  },
  {
    id: "task-004",
    documentId: "d-011",
    documentName: "主汽阀 MV-201 检修工艺卡.pdf",
    documentNo: "DOC-2026-0115",
    fileType: "PDF",
    totalPages: 1,
    currentPage: 1,
    candidates: [
      {
        id: "cand-11",
        pageNo: 1,
        label: "阀盖螺栓 M16×70",
        status: "pending",
        bbox: { x: 45, y: 25 },
        isPart: true,
        candidateType: "零件",
        partAttributes: { ...baseAttrs, partNo: "V201-009", name: "阀盖螺栓", spec: "M16×70 8.8级", material: "合金钢", unit: "2#机组", system: "蒸汽系统", device: "主汽阀 MV-201", installLocation: "阀盖", category: "机械", level: "B级", importance: "重要", radiationRisk: "中" },
      },
      {
        id: "cand-12",
        pageNo: 1,
        label: "扭矩要求 180N·m",
        status: "skipped",
        bbox: { x: 60, y: 65 },
        isPart: false,
        candidateType: "操作步骤",
        partAttributes: { ...baseAttrs },
      },
    ],
  },
];
